<#import "parts/common.ftlh" as c>
<#import "parts/login.ftlh" as l>

<@c.page>
<div class="card col-sm-2">
    <div>
<#--        <p><i>Please use <span style="color: red;">user</span> as Login</i></p>-->
<#--        <p><i>Please use <span style="color: red;">user</span> as Password</i></p>-->
        <p><i>Welcome to FazeWay Sales Book </i></p>
        <a href="/main">Dive in</a>
    </div>
</div>

</@c.page>